databases:
  - name: servicehub-db
    plan: free

services:
  - type: web
    name: servicehub
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: servicehub-db
          property: connectionString
      - key: APP_URL
        value: https://REPLACE_ME.onrender.com
      - key: ASSET_URL
        value: https://REPLACE_ME.onrender.com
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.mailgun.org
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: postmaster@YOUR_DOMAIN
      - key: MAIL_PASSWORD
        value: YOUR_MAILGUN_SMTP_PASSWORD
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: no-reply@YOUR_DOMAIN
      - key: MAIL_FROM_NAME
        value: ServiceHub

